# custom_components/ai_automation_suggester/services.yaml

generate_suggestions:
  name: Generate Suggestions
  description: "Manually trigger AI automation suggestions."
  fields:
    provider_config:
      name: Provider Configuration
      description: Which provider configuration to use (if you have multiple configured)
      required: false
      selector:
        config_entry:
          integration: ai_automation_suggester
    custom_prompt:
      name: Custom Prompt
      description: Optional custom prompt to override the default system prompt
      required: false
      example: "Generate automations focusing on energy savings and security"
      selector:
        text:
          multiline: true
