name: Hassfest
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" 
jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "home-assistant/actions/hassfest@master"
